#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : icecream
Version  : 1.4
Release  : 11
URL      : https://github.com/icecc/icecream/releases/download/1.4/icecc-1.4.0.tar.xz
Source0  : https://github.com/icecc/icecream/releases/download/1.4/icecc-1.4.0.tar.xz
Source1  : iceccd.service
Source2  : icecream-scheduler.service
Source3  : icecream.sh
Summary  : icecc is a library for connecting to icecc schedulers
Group    : Development/Tools
License  : GPL-2.0
Requires: icecream-bin = %{version}-%{release}
Requires: icecream-data = %{version}-%{release}
Requires: icecream-libexec = %{version}-%{release}
Requires: icecream-license = %{version}-%{release}
Requires: icecream-services = %{version}-%{release}
BuildRequires : lzo-dev
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libcap-ng)
BuildRequires : pkgconfig(libzstd)
Patch1: 0001-Update-icecc-create-env-to-support-glibc-hwcaps.patch

%description
NOTE: Although icecream will compile on some non-Linux systems,
it depends critically on Linux' /proc/ structures and will fail
at runtime until somebody figures out how to emulate the "ticks"
form of process accounting in there.

%package bin
Summary: bin components for the icecream package.
Group: Binaries
Requires: icecream-data = %{version}-%{release}
Requires: icecream-libexec = %{version}-%{release}
Requires: icecream-license = %{version}-%{release}
Requires: icecream-services = %{version}-%{release}

%description bin
bin components for the icecream package.


%package data
Summary: data components for the icecream package.
Group: Data

%description data
data components for the icecream package.


%package dev
Summary: dev components for the icecream package.
Group: Development
Requires: icecream-bin = %{version}-%{release}
Requires: icecream-data = %{version}-%{release}
Provides: icecream-devel = %{version}-%{release}
Requires: icecream = %{version}-%{release}

%description dev
dev components for the icecream package.


%package libexec
Summary: libexec components for the icecream package.
Group: Default
Requires: icecream-license = %{version}-%{release}

%description libexec
libexec components for the icecream package.


%package license
Summary: license components for the icecream package.
Group: Default

%description license
license components for the icecream package.


%package services
Summary: services components for the icecream package.
Group: Systemd services

%description services
services components for the icecream package.


%prep
%setup -q -n icecc-1.4.0
cd %{_builddir}/icecc-1.4.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1651516003
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --with-man=no
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1651516003
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/icecream
cp %{_builddir}/icecc-1.4.0/COPYING %{buildroot}/usr/share/package-licenses/icecream/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/iceccd.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/icecream-scheduler.service
mkdir -p %{buildroot}/usr/share/defaults/etc/profile.d
install -m755 %{_sourcedir}/icecream.sh %{buildroot}/usr/share/defaults/etc/profile.d/30-icecream.sh
## install_append content
# Add a few more symlinks to compilers we have in Clear
# (and ensure others exist)
set clang clang++ x86_64-generic-linux-c++ x86_64-generic-linux-gcc x86_64-generic-linux-g++
for f; do
ln -sf /usr/bin/icecc %{buildroot}/usr/libexec/icecc/bin/$f
done
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/icecc
/usr/bin/icecc-create-env
/usr/bin/icecc-scheduler
/usr/bin/icecc-test-env
/usr/bin/iceccd
/usr/bin/icerun

%files data
%defattr(-,root,root,-)
/usr/share/defaults/etc/profile.d/30-icecream.sh

%files dev
%defattr(-,root,root,-)
/usr/include/icecc/comm.h
/usr/include/icecc/job.h
/usr/include/icecc/logging.h
/usr/lib64/pkgconfig/icecc.pc

%files libexec
%defattr(-,root,root,-)
/usr/libexec/icecc/bin/c++
/usr/libexec/icecc/bin/cc
/usr/libexec/icecc/bin/clang
/usr/libexec/icecc/bin/clang++
/usr/libexec/icecc/bin/g++
/usr/libexec/icecc/bin/gcc
/usr/libexec/icecc/bin/x86_64-generic-linux-c++
/usr/libexec/icecc/bin/x86_64-generic-linux-g++
/usr/libexec/icecc/bin/x86_64-generic-linux-gcc
/usr/libexec/icecc/compilerwrapper
/usr/libexec/icecc/icecc-create-env

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/icecream/4cc77b90af91e615a64ae04893fdffa7939db84c

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/iceccd.service
/usr/lib/systemd/system/icecream-scheduler.service
